In [3]:
from tensorflow.keras.models import load_model
import pickle
from pickle import load

In [9]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [25]:
data = [90,42,43,20.879744,82.002744,6.502985,202.935536]
X = np.array(data)
X

array([[ 90.      ,  42.      ,  43.      ,  20.879744,  82.002744,
          6.502985, 202.935536]])

In [26]:
scaler = load(open('minMaxScaler.pkl', 'rb'))
X = scaler.transform(X.reshape(1, -1))
X

/opt/anaconda3/envs/patrika/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  "X does not have valid feature names, but"


array([[0.64285714, 0.26428571, 0.19      , 0.34588614, 0.79022954,
        0.46626359, 0.6562741 ]])

In [27]:
model = load_model('cropPredictor.h5')
y_preds = model.predict(np.array(data).reshape(1,-1))
y_preds

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.]], dtype=float32)

In [12]:
label_index = np.argmax(y_preds, axis=1).tolist()
label_index

[1]

In [14]:
encoding = pickle.load(open('encoding.pkl', 'rb'))
encoding[label_index[0]]

'banana'

In [20]:
def suggestCrop(N, P, K, temp, humidity, ph, rainfall):
    data = [N, P, K, temp, humidity, ph, rainfall]
    X = np.array([data])

    model = load_model('cropPredictor.h5')
    encoding = pickle.load(open('encoding.pkl', 'rb'))

    scaler = load(open('minMaxScaler.pkl', 'rb'))
    X = scaler.transform(X.reshape(1, -1))

    print(X)

    res = model.predict(X)
    label_index = np.argmax(res, axis=1).tolist()

    suggested_crop = encoding[label_index[0]]

    return {'status':'OK','suggested_crop':suggested_crop}

In [36]:
suggestCrop(6,
77,
20,
25.78746268,
60.2816298,
6.058306161,
49.14337177)

[[0.04285714 0.51428571 0.075      0.48671094 0.53679971 0.39711034
  0.10346279]]


/opt/anaconda3/envs/patrika/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  "X does not have valid feature names, but"


{'status': 'OK', 'suggested_crop': 'papaya'}